### ISSUE TITLE
skip header information (a number of lines)?

### ISSUE THREAD

**Issue by vonbecmann** [svenvc/NeoCSV#10]
ConfigurationOfNeoCSV project currentVersion  "15 [ConfigurationOfNeoCSV]"

i wrote several times this code

"skip header information"
7 timesRepeat: [ reader next ].

do you think that a kind of skip method  could be added to NeoCSVReader? is it appropiate?

thanks for neocsv. really useful.

**Comment by svenvc** [comment]
There is already a method called #skipHeader

Would that help you ?

I am curious though how a header can be multiple lines though ?

**Comment by vonbecmann** [comment]
it has useless information, then it has a header and then comes the data. something like this

,,,,,
"Lista: ED-MAR Electricidad S.A.",,,,02/14/2020,
,,,,,
0,"INGRESE SU BONIFICACION EN LA CELDA ANTERIOR   A 4",,,,
0,"INGRESE SU DESCUENTO  POR PAGO EN LA CELDA ANTERIOR  A 5",,,,
0,"INGRESE SU UTILIDAD CON EL IVA EN LA CELDA ANTERIOR  A 6",,,,
"Nota: para buscar un articulo por codigo vaya a EDICION, haga click en BUSCAR;",,,,,
"coloque el codigo deseado  y haga click en BUSCAR SIGUIENTE, o presione ENTER",,,,,
,,,,,
"CODIGO","DESCRIPCION","T.Iva","LISTA","NETO","VENTA"
,,,,,
"002101","Terminal Macho  REFORZADO PIDG 16-14 6,3mm  140971-2",21,43.056,43.056,43.056
"002108","Terminal Hembra REFORZADO PIDG 12-10 6,3mm  160314-2",21,57.914,57.914,57.914
"002110","Terminal Macho  REFORZADO PIDG 12-10 6,3mm  141085-2",21,62.479,62.479,62.479

**Comment by vonbecmann** [comment]
attached as a txt file
[edmar-price-list.txt](https://github.com/svenvc/NeoCSV/files/4220204/edmar-price-list.txt)

**Comment by svenvc** [comment]
Can you try https://github.com/svenvc/NeoCSV/commit/caa7a389a3a16518f6136788f8d8a24685b5a69a ?

**Comment by vonbecmann** [comment]
i did it. but my reply is in the commit. see [https://github.com/svenvc/NeoCSV/commit/caa7a389a3a16518f6136788f8d8a24685b5a69a#commitcomment-37386573](url)

**Comment by svenvc** [comment]
thx for the feedback !
