### ISSUE TITLE
CI to Run Tests

### ISSUE THREAD

**Issue by seandenigris** [svenvc/NeoCSV#18]
Any interest? IIRC it is fairly easy to set up and I'm willing to give it a try...

**Comment by svenvc** [comment]
That is already happening, see

https://travis-ci.org/github/svenvc/NeoCSV
https://github.com/svenvc/NeoCSV/blob/master/.travis.yml
https://github.com/svenvc/NeoCSV/blob/master/.smalltalk.ston

Or did you mean specifically for Magritte ?

**Comment by seandenigris** [comment]
Oops sorry! Although while we’re on the subject I see many projects switching from Travis to Actions. Not sure why the latter is better...
