### ISSUE TITLE
question: would you move to pharo8? when? is that possible?

### ISSUE THREAD

**Issue by vonbecmann** [svenvc/NeoCSV#21]
**thank you  very much**. im using this library all the time.

**Comment by svenvc** [comment]
HI,

I know that I have to change all my Travis CI builds to GutHub Actions and that there was only a Pharo 7 built, but as far as I know, there should be no problem loading and running the code in Pharo 8 or 9. Did you encounter any issues ?

Sven

**Comment by vonbecmann** [comment]
i try the pull request with pharo8 and there is no problem in the CI.  that's all i know. thanks. however i need to check others libraries in pharo8. thanks.

**Comment by svenvc** [comment]
The current GitHub Actions run for 7, 8 and 9
