### ISSUE TITLE
Integers with commas

### ISSUE THREAD

**Issue by tsl4** [svenvc/NeoCSV#27]
Oh hello. Perhaps I've missed something, but if you do add an integer field to process a CSV value such as 29,492, the result you get is 29, as the parsing stops when the parser encounters the non-integer comma used as a thousands seperator.

Rather hideously, I have temporarily patched this with a new method: 

addIntegerFieldWithCommas
	"Add a field for indexable records parsed as Integer, compensate for commas"
	self addFieldConverter: [ :string | NeoNumberParser parse: (string copyReplaceAll: ','  with: '') ]

... which is, of course, slightly horrific. I spent some time looking at NeoNumberParser, and really enjoyed what you've done there, setting string as an instance variable, and then your use of next and on — really felt I learned something.

So, do you think that parseNumber should be changed? But we end up getting into internationalisation as well, as the thousands separator varies, though the international standard is a space — which I think makes more sense.

Anyway, would be very interested to see how you think about this.

**Comment by svenvc** [comment]
I think you are looking for something along the lines of
```
NeoCSVReader>>#addFloatFieldRadixPointComma
	"Add a field for indexable records parsed as Float using a comma as radix point"

	self addFieldConverter: [ :string | (NeoNumberParser on: string) radixPoint: $, ; next ]
```
but not for the radix point but for the thousands separator ?

That should indeed be added to NeoNumberParser.

Skipping/ignoring a 'digit grouping' separator without validation (!) would not be too hard to add I guess.

https://en.wikipedia.org/wiki/Decimal_separator#Digit_grouping

**Comment by svenvc** [comment]
See https://github.com/svenvc/NeoCSV/commit/10356a2b1e3c51aa1fac096458a354f965dacff7
