### ISSUE TITLE
FileReference>>csvReaderDo: opinion??

### ISSUE THREAD

**Issue by vonbecmann** [svenvc/NeoCSV#28]
hi, is this a good extension? what's your opinion?
```
'From Pharo7.0.4 of 23 November 2019 [Build information: Pharo-7.0.4+build.175.sha.fd8c156d959653f52be6fd7f8c71edf8cfb8fe90 (32 Bit)] on 5 December 2021 at 12:26:56.345844 pm'!

!FileReference methodsFor: '*HWStore-Core' stamp: 'BernardoContreras 11/26/2021 23:48'!
csvReaderDo: aBlock
	| reader |
	^ self
		readStreamDo: [ :stream | 
			reader := NeoCSVReader on: stream.
			[ aBlock value: reader ]
				ensure: [ reader close ] ]! !

```

**Comment by svenvc** [comment]
Hi,

Yes, that would make total sense.

Initially I did not do this because I did not want to create hooks/dependencies into existing classes, but a small amount of these can make live easier.

I will consider it, we would need a csvWriterDo: too and tests.

Sven

**Comment by vonbecmann** [comment]
yes,  you need FileReference from pharo, that's a problem. now i see. managing projects is a big problem. 

im about to add csvWriterDo: in my little project because i have code duplication. 

in any case thanks.
