### ISSUE TITLE
CSVReader>>#reject: and #reject:thenDo: ?

### ISSUE THREAD

**Issue by vonbecmann** [svenvc/NeoCSV#29]
are those useful? what's your opinion?

**Comment by svenvc** [comment]
Hi,

Yes this makes sense.

https://github.com/svenvc/NeoCSV/commit/8f04cf01e32529d6b451927de2d4c73b9bc41d37

Thx !

Sven

**Comment by vonbecmann** [comment]
nice, thanks. this can be close now.
