### ISSUE TITLE
CSV using non-standard value for empty fields

### ISSUE THREAD

**Issue by seandenigris** [svenvc/NeoCSV#30]
I have data that uses `'NULL'` to represent missing values. Is there a way to configure a reader to accept that as an empty field? Or to generally convert that value to nil without defining each field?

**Comment by seandenigris** [comment]
I was hoping for a global (i.e. per reader instead of per field) companion to `#emptyFieldValue:` that specifies the *input* for which `#emptyFieldValue:`  applies, so I wouldn't have to define each field individually. If non-empty missing values are not common in the CSV world, I understand it may not be worth it.

**Comment by svenvc** [comment]
Can this be closed ?

**Comment by seandenigris** [comment]
I'd still like to have the feature. I wasn't sure if my previous comment clarified the intent. What do you think?

**Comment by svenvc** [comment]
https://github.com/svenvc/NeoCSV/commit/cca7fbbb400231054c8792492be69288df15aa88

Does this work for you ?

**Comment by seandenigris** [comment]
That looks like exactly what I was hoping for! Thanks :)
