### ISSUE TITLE
NeoCSVReader : cannot read string with not embedded double quotes 

### ISSUE THREAD

**Issue by labordep** [svenvc/NeoCSV#34]
I'm trying to parse a generated file (so I haven't the control of the generation format) which contains this line :
 
`"NES","VideoGame",1,0,0,"Ivan "Ironman" Stewart's Super Off Road","Tradewest, Inc.","Rare, Ltd.","22/03/2021"`

And the parsing is blocking on `"Ivan "Ironman" Stewart's Super Off Road"` because of the embedded quote is not double :(

Try this code to understand :
`(NeoCSVReader on: '0,"Ivan "Ironman" Stewart''s Super Off Road",1' readStream) separator: $,; upToEnd`
Should be 3 items and not 4.

Do you have a way to parse this line using settings ? For the moment I prefer not to modify the entry file.

**Comment by svenvc** [comment]
I do not think this is possible. 

Look at the NeoCSVReader>>#readField

Once the opening quote is seen, the logic kicks in, including the doubling for embedded quotes.

Maybe you could try subclassing and overriding some of this logic: read all fields unquoted and remove the prefix/postfix quotes ?

On the other hand, the quoting is there to allow embedded commas, you cannot have both.
