### ISSUE TITLE
Parsing Floats with $, as decimal point character 

### ISSUE THREAD

**Issue by jmari** [svenvc/NeoCSV#5]
In R you can change the floating point character $. by other character using
read.csv("file.csv",dec=",")
I think it is useful. You should add a decimal: aChar method to NeoCSVReader and change NeoNumberParser to be able to parse float numbers separated by the assigned "decimal point" character.

**Comment by svenvc** [comment]
Hi,

I implemented your feature request as follow:

Name: Neo-CSV-Core-SvenVanCaekenberghe.28
Author: SvenVanCaekenberghe
Time: 25 April 2018, 1:47:14.911896 pm
UUID: 455db591-0c27-0d00-94e0-a4610fb94961
Ancestors: Neo-CSV-Core-SvenVanCaekenberghe.27

Add NeoNumberParser>>#radixPoint:

Add NeoCSVReader>>#addFloatFieldRadixPointComma and NeoCSVReader>>#addFloatFieldRadixPointCommaAt:

Add relevant unit tests

This should make it easier to parse Euro formatted floats.
