### ISSUE TITLE
Doesn't load via Metacello into Squeak 5.2

### ISSUE THREAD

**Issue by tcj** [svenvc/NeoCSV#7]
Trying the following in Squeak:

```
Metacello new
  repository: 'github://svenvc/NeoCSV/repository';
  baseline: 'NeoCSV';
  load.
```

Results in:

```
MetacelloFetchingMCSpecLoader(MetacelloCommonMCSpecLoader)>>retryingResolvePackageSpecReferences:gofer:
[] in MetacelloFetchingMCSpecLoader>>linearLoadPackageSpec:gofer:
[] in MetacelloSqueakPlatform>>do:displaying:
[] in [] in MorphicUIManager>>displayProgress:at:from:to:during:
BlockClosure>>on:do:
[] in MorphicUIManager>>displayProgress:at:from:to:during:
BlockClosure>>ensure:
MorphicUIManager>>displayProgress:at:from:to:during:
ProgressInitiationException>>defaultResumeValue
ProgressInitiationException(Exception)>>resume
ProgressInitiationException>>defaultAction
UndefinedObject>>handleSignal:
Context>>handleSignal:
Context>>handleSignal:
Context>>handleSignal:
Context>>handleSignal:
Context>>handleSignal:
Context>>handleSignal:
ProgressInitiationException(Exception)>>signal
ProgressInitiationException>>display:at:from:to:during:
```

I've tried to get to the bottom of this, but I can't quite figure it out.  It seems like Metacello is searching for a `*.mcz` file inside of a repository cache — but my guess is that it shouldn't be, since this is a GitHub repo and it is cached in `github-cache` directory, not `package-cache` directory, and it won't have any `*.mcz` files.  The repo does definitely get downloaded correctly, but it also seems like when I poke around in the debugger, Metacello can't find the `BaselineOfNeoCSV` directory on disk.

**Comment by svenvc** [comment]
I am not sure this is an NeoCSV specific issue.

You are trying to load a GitHub+Tonel repo where I doubt such support exists.

**Comment by tcj** [comment]
Whoops!  Didn't know it was Tonel.  Sorry, thanks, and nevermind.
